apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaledobject
  namespace: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicaCount: 1
  maxReplicaCount: 4
  cooldownPeriod: 15
  pollingInterval: 5
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        consumerGroup: video-converter-group
        topic: task_queue
        lagThreshold: "10"
