global:
   scrape_interval: 10s

scrape_configs:
- job_name: myminio
  bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoibWluaW8iLCJleHAiOjQ4ODk1OTI3ODJ9.pabrErIjQxjrgGE0Ultvpg-XOaYyGr_HXWoCEaRb2wHbraHxvmyu0TgY8uKj8CGoDeo-n8a0fU1nDiN0kTVUaA
  metrics_path: /minio/v2/metrics/cluster
  scheme: http
  static_configs:
  - targets: ['minio.minio.svc.cluster.local:9000']
