apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-monitor
  namespace: monitoring
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-metrics
  namespaceSelector:
    matchNames:
      - kafka
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
