apiVersion: v1
kind: Service
metadata:
  name: kafka-metrics
  namespace: kafka
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9404"
  labels:
    app.kubernetes.io/name: kafka-metrics
spec:
  selector:
    app.kubernetes.io/name: kafka
  ports:
    - name: metrics
      protocol: TCP
      port: 9404
      targetPort: 9404
