apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-kafka
  namespace: kafka
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-kafka
  namespace: kafka
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: monitoring
roleRef:
  kind: Role
  name: prometheus-kafka
  apiGroup: rbac.authorization.k8s.io
